### ISSUE TITLE
No such bucket error encountered

### ISSUE THREAD

**Issue by tuxdna** [fabric8-analytics/fabric8-analytics-data-model#74]
Start the import :

http://localhost:32000/api/v1/component-analyses/maven/org.apache.tomcat:tomcat-servlet-api/8.5.6

Data import into graph fails for a  package: /maven/org.apache.tomcat:tomcat-servlet-api/8.5.6

```
data-model-importer_1   | --------------------------------------------------------------------------------
data-model-importer_1   | INFO in rest_api [/src/rest_api.py:94]:
data-model-importer_1   | Ingesting the given list of EPVs - [{"ecosystem": "maven", "version": "8.5.6", "name": "org.apache.tomcat:tomcat-servlet-api"}]
data-model-importer_1   | --------------------------------------------------------------------------------
data-model-importer_1   | ERROR:data_importer:import_epv() failed with error: An error occurred (NoSuchBucket) when calling the ListObjects operation: The specified bucket does not exist
data-model-importer_1   | ERROR:data_importer:Traceback for latest failure in import call: Traceback (most recent call last):
data-model-importer_1   |   File "/src/data_importer.py", line 164, in import_epv_http
data-model-importer_1   |     prefix=pkg_key_prefix))
data-model-importer_1   |   File "/src/data_source/s3_data_source.py", line 66, in list_files
data-model-importer_1   |     for obj in bucket.objects.filter(Prefix=prefix):
data-model-importer_1   |   File "/usr/lib/python2.7/site-packages/boto3/resources/collection.py", line 83, in __iter__
data-model-importer_1   |     for page in self.pages():
data-model-importer_1   |   File "/usr/lib/python2.7/site-packages/boto3/resources/collection.py", line 166, in pages
data-model-importer_1   |     for page in pages:
data-model-importer_1   |   File "/usr/lib/python2.7/site-packages/botocore/paginate.py", line 255, in __iter__
data-model-importer_1   |     response = self._make_request(current_kwargs)
data-model-importer_1   |   File "/usr/lib/python2.7/site-packages/botocore/paginate.py", line 332, in _make_request
data-model-importer_1   |     return self._method(**current_kwargs)
data-model-importer_1   |   File "/usr/lib/python2.7/site-packages/botocore/client.py", line 317, in _api_call
data-model-importer_1   |     return self._make_api_call(operation_name, kwargs)
data-model-importer_1   |   File "/usr/lib/python2.7/site-packages/botocore/client.py", line 615, in _make_api_call
data-model-importer_1   |     raise error_class(parsed_response, operation_name)
data-model-importer_1   | NoSuchBucket: An error occurred (NoSuchBucket) when calling the ListObjects operation: The specified bucket does not exist
data-model-importer_1   | [2018-01-31 11:29:48 +0000] [70] [ERROR] Error handling request /api/v1/ingest_to_graph
data-model-importer_1   | Traceback (most recent call last):
data-model-importer_1   |   File "/usr/lib/python2.7/site-packages/gunicorn/workers/async.py", line 56, in handle
data-model-importer_1   |     self.handle_request(listener_name, req, client, addr)
data-model-importer_1   |   File "/usr/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 152, in handle_request
data-model-importer_1   |     super(GeventWorker, self).handle_request(*args)
data-model-importer_1   |   File "/usr/lib/python2.7/site-packages/gunicorn/workers/async.py", line 107, in handle_request
data-model-importer_1   |     respiter = self.wsgi(environ, resp.start_response)
data-model-importer_1   |   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1997, in __call__
data-model-importer_1   |     return self.wsgi_app(environ, start_response)
data-model-importer_1   |   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
data-model-importer_1   |     response = self.handle_exception(e)
data-model-importer_1   |   File "/usr/lib64/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
data-model-importer_1   |     return cors_after_request(app.make_response(f(*args, **kwargs)))
data-model-importer_1   |   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
data-model-importer_1   |     reraise(exc_type, exc_value, tb)
data-model-importer_1   |   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
data-model-importer_1   |     response = self.full_dispatch_request()
data-model-importer_1   |   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
data-model-importer_1   |     rv = self.handle_user_exception(e)
data-model-importer_1   |   File "/usr/lib64/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
data-model-importer_1   |     return cors_after_request(app.make_response(f(*args, **kwargs)))
data-model-importer_1   |   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
data-model-importer_1   |     reraise(exc_type, exc_value, tb)
data-model-importer_1   |   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
data-model-importer_1   |     rv = self.dispatch_request()
data-model-importer_1   |   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
data-model-importer_1   |     return self.view_functions[rule.endpoint](**req.view_args)
data-model-importer_1   |   File "/src/rest_api.py", line 102, in ingest_to_graph
data-model-importer_1   |     report = data_importer.import_epv_from_s3_http(list_epv=input_json)
data-model-importer_1   |   File "/src/data_importer.py", line 214, in import_epv_from_s3_http
data-model-importer_1   |     list_epv, select_doc)
data-model-importer_1   |   File "/src/data_importer.py", line 199, in import_epv_http
data-model-importer_1   |     raise RuntimeError(msg)
data-model-importer_1   | RuntimeError: import_epv() failed with error: An error occurred (NoSuchBucket) when calling the ListObjects operation: The specified bucket does not exist
data-model-importer_1   | --------------------------------------------------------------------------------
data-model-importer_1   | INFO in rest_api [/src/rest_api.py:94]:
data-model-importer_1   | Ingesting the given list of EPVs - [{"ecosystem": "maven", "version": null, "name": "org.apache.tomcat:tomcat-servlet-api"}]

```

**Comment by jpopelka** [comment]
Yeah, I think I've seen that too.
Would be nice if the data_importer could cope with the non-existing bucket.
But if it really needs the bucket to be there,
then for local testing we have [fabric8-analytics-cvedb-s3-dump-docker](https://github.com/fabric8-analytics/fabric8-analytics-cvedb-s3-dump-docker), which uploads data to minio (local S3 equivalent) when starting whole f8a via docker-compose.

**Comment by tuxdna** [comment]
I could reproduce the error again. However it seems like the bucket gets created once we analyze some other package, and later force analyze ( using curl -X POST ) the first package again. 

Therefore, the bucket is getting created after it is required the first time by data importer.

**Comment by msrb** [comment]
> Therefore, the bucket is getting created after it is required the first time by data importer.

This is weird, isn't it? It sounds like some logical error somewhere. Do we know what bucket is missing?

**Comment by msrb** [comment]
This issue was moved to openshiftio/openshift.io#2219
