### ISSUE TITLE
Gremlin queries are timing out in prod

### ISSUE THREAD

**Issue by tuxdna** [fabric8-analytics/fabric8-analytics-data-model#75]
Over 100 instances of **Timing out** messages in logs are encountered as shown below

```
Timing out script - g.V().has('ecosystem',ecosystem).has('name',within(input_packages)).as('pkg').out('has_version').hasNot('cve_ids').as('ver').select('pkg','ver').by(valueMap()).dedup() - in thread [gremlin-server-worker-1]
45814468 [gremlin-server-worker-1] WARN  org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor  - Timing out script - g.V().has('ecosystem',ecosystem).has('name',within(input_packages)).as('pkg').out('has_version').hasNot('cve_ids').as('ver').select('pkg','ver').by(valueMap()).dedup() - in thread [gremlin-server-worker-1]
45815205 [gremlin-server-exec-4] WARN  org.apache.tinkerpop.gremlin.server.handler.HttpGremlinEndpointHandler  - Invalid request - responding with 500 Internal Server Error and Error encountered evaluating script: g.V().has('ecosystem',ecosystem).has('name',within(input_packages)).as('pkg').out('has_version').hasNot('cve_ids').as('ver').select('pkg','ver').by(valueMap()).dedup()
org.apache.tinkerpop.gremlin.process.traversal.util.TraversalInterruptedException
	at com.thinkaurelius.titan.diskstorage.BackendTransaction.executeRead(BackendTransaction.java:434)
	at com.thinkaurelius.titan.diskstorage.BackendTransaction.edgeStoreQuery(BackendTransaction.java:254)
	at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.edgeQuery(StandardTitanGraph.java:413)
	at com.thinkaurelius.titan.graphdb.query.vertex.SimpleVertexQueryProcessor$2.lambda$get$0(SimpleVertexQueryProcessor.java:114)
	at com.thinkaurelius.titan.graphdb.query.profile.QueryProfiler.profile(QueryProfiler.java:84)
	at com.thinkaurelius.titan.graphdb.query.profile.QueryProfiler.profile(QueryProfiler.java:76)
	at com.thinkaurelius.titan.graphdb.query.profile.QueryProfiler.profile(QueryProfiler.java:68)
	at com.thinkaurelius.titan.graphdb.query.vertex.SimpleVertexQueryProcessor$2.get(SimpleVertexQueryProcessor.java:114)
	at com.thinkaurelius.titan.graphdb.query.vertex.SimpleVertexQueryProcessor$2.get(SimpleVertexQueryProcessor.java:111)
	at com.thinkaurelius.titan.graphdb.vertices.CacheVertex.loadRelations(CacheVertex.java:53)
	at com.thinkaurelius.titan.graphdb.query.vertex.SimpleVertexQueryProcessor.getBasicIterator(SimpleVertexQueryProcessor.java:111)
	at com.thinkaurelius.titan.graphdb.query.vertex.SimpleVertexQueryProcessor.iterator(SimpleVertexQueryProcessor.java:68)
	at com.thinkaurelius.titan.graphdb.transaction.RelationConstructor$1$1.<init>(RelationConstructor.java:36)
	at com.thinkaurelius.titan.graphdb.transaction.RelationConstructor$1.iterator(RelationConstructor.java:34)
	at com.thinkaurelius.titan.graphdb.vertices.AbstractVertex.properties(AbstractVertex.java:160)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.PropertyMapStep.map(PropertyMapStep.java:67)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.PropertyMapStep.map(PropertyMapStep.java:46)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.MapStep.processNextStart(MapStep.java:37)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:128)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:38)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.next(DefaultTraversal.java:186)
	at org.apache.tinkerpop.gremlin.process.traversal.util.TraversalUtil.apply(TraversalUtil.java:93)
	at org.apache.tinkerpop.gremlin.process.traversal.util.TraversalUtil.applyNullable(TraversalUtil.java:119)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.SelectStep.map(SelectStep.java:69)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.SelectStep.map(SelectStep.java:46)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.MapStep.processNextStart(MapStep.java:37)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.SelectStep.processNextStart(SelectStep.java:158)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.ExpandableStepIterator.next(ExpandableStepIterator.java:50)
	at org.apache.tinkerpop.gremlin.process.traversal.step.filter.FilterStep.processNextStart(FilterStep.java:37)
	at org.apache.tinkerpop.gremlin.process.traversal.step.filter.DedupGlobalStep.processNextStart(DedupGlobalStep.java:92)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:179)
	at org.apache.tinkerpop.gremlin.util.iterator.IteratorUtils.fill(IteratorUtils.java:62)
	at org.apache.tinkerpop.gremlin.util.iterator.IteratorUtils.list(IteratorUtils.java:85)
	at org.apache.tinkerpop.gremlin.util.iterator.IteratorUtils.asList(IteratorUtils.java:382)
	at org.apache.tinkerpop.gremlin.server.handler.HttpGremlinEndpointHandler.lambda$channelRead$1(HttpGremlinEndpointHandler.java:239)
	at org.apache.tinkerpop.gremlin.util.function.FunctionUtils.lambda$wrapFunction$0(FunctionUtils.java:36)
	at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$2(GremlinExecutor.java:293)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

Some of the queries identified as timing out are:

```
 g.V().has('ecosystem',ecosystem).has('name',within(input_packages)).as('pkg').out('has_version').hasNot('cve_ids').as('ver').select('pkg','ver').by(valueMap()).dedup() - in thread [gremlin-server-worker-1]

 g.V().has('pecosystem', 'maven').has('pname', 'io.vertx:vertx-core').has('version', '3.4.1').as('version').in('has_version').as('package').select('version','package').by(valueMap()); - in thread [gremlin-server-worker-1]

 g.V().has('pecosystem', 'maven').has('pname', 'io.vertx:vertx-web').has('version', '3.4.1').as('version').in('has_version').as('package').select('version','package').by(valueMap()); - in thread [gremlin-server-worker-1]

 g.V().has('pecosystem', 'maven').has('pname', 'io.vertx:vertx-web-client').has('version', '3.4.1').as('version').in('has_version').as('package').select('version','package').by(valueMap()); - in thread [gremlin-server-worker-1]

```

**Comment by tuxdna** [comment]
Following are the candidate locations from these queries are invoked:

 https://github.com/fabric8-analytics/fabric8-analytics-worker/blob/2726d3c9b88f5618cd553405370d732e3867e090/f8a_worker/workers/stackaggregator_v2.py#L338-L351

https://github.com/fabric8-analytics/fabric8-analytics-worker/blob/2726d3c9b88f5618cd553405370d732e3867e090/f8a_worker/workers/stackaggregator.py#L129-L140

https://github.com/fabric8-analytics/fabric8-analytics-worker/blob/2726d3c9b88f5618cd553405370d732e3867e090/f8a_worker/workers/recommender.py#L271-L288

**Comment by tuxdna** [comment]
This issue was resolved in prod.
